### ISSUE TITLE
Github source structure (and how to manage via RDi)

### ISSUE THREAD

**Issue by priceaj** [ChrisHird/intERPrise#15] opened 2018-11-28 10:13 UTC
Chris, can you explain how the project is to be structured in the Repo going forward so that we can document a consistent process for import into RDi?

From how it was structured initially I thought the git repo was matching a single RDi Project, so I'd expect a flat tree i.e. 
* repo = library
* folders = Source files
* source files = source members 

So in RDi I would have a Single intERPrise iProject linked to a single library and the source would pull in from git and just overlay a single library on the i. 

With the addition of the Transport_Services folder (and EXAMPLE), this is no longer the case.

I'd expect the repo to be structured in one of 3 ways:
* code for this to either be held in the same source files (or differently named ones in the flat structure), 
* each module to be in a different Repo entirely (so a second iproject could be created), 
* if individual projects are to be created from folders within this repo I'd expect to see each "module" in a separate folder.

It's possible I'm just not using Git with RDi correctly, if so can you explain how you have this structured, and how we should be importing this project into RDi?

I think it's important to establish this at this early point in the project so that a large amount of restructuring is not required at a later date, also if there is a consistent way of importing the project it will make it easier for people (like me) who have not used iProjects with git before.

**Comment by ChrisHird** [comment] 2018-11-28 13:37
The use of RDi is optional so the method of structuring the code for iProject inclusion is not something we can dictate. We have had numerous requests to have all of the code stored in the IFS so that deeper nesting can be achieved and so allow a "better" naming convention? The development environment I have set up allows the code to be delivered with deeper nesting using iProjects without forcing the use of the IFS (see other discussions on the use of the IFS or not).

I have set up RDi so the *LOCAL git repository is store in the same directory as the iProject content on my PC. To achieve this I use 2 iProjects (could expand later) One points to Library IRP (DB source etc) and has a PC storage of /Projects/intERPrise, the other points to Library IRPT (transport services source) and has a PC storage of /Projects/intERPrise/Transport_Services. 

The initial clone of the Git Repository should be made before adding the iProjects (otherwise you get conflicts due to iProject content being there before the clone occurs).  Once this is done the PULL request to the relevant branch should be made before any changes are mode. (We are always updating. You will also notice I have created a separate branch (Chris_Transport) where I will now make all of my changes and merge with the master on a frequent basis.

Personally I make changes in Remote explorer and copy to the PC via the Add to iProject option (will prompt replace if already exists), this will update the PC Files and cause git to recognize the file changes allowing me to identify the changes and select for commit and push.

I hope that explains my solution to one of segregation, the code we supply should be able to be used within the IFS structure or the Library structure (personal choice), however the build programs are developed suing the library base only.

Hope that helps. If you would like to offer alternatives we will be happy to hear them, but the development environment must always be personal choice.

**Comment by priceaj** [comment] 2018-11-28 16:10
I have my iProject linked directly to my Git sources so I'm doing work on RDi directly through iProjects any changes made in RDi automatically updates the git repo with my changes (which then need to be committed). Taking the right click> remote actions> compile (or Push Changes) option from the iProject pushes the source to the Linked library on the i. 

The problem with this project was is that when i pulled in the new commits a Transport_Services Source File appeared in iProjects which contained the readme.md. 

This is because the project does not have a consistent structure at present. At the moment the source files for the part which @Mbogo33 has done is at the same level as the Transport_services folder, so iProjects thinks the folder is a Source file!

I've suggested three ways this could be better structured so that this does not happen:

* code to be held in the same source files (or differently named ones in a flat structure)
* each module to be in a different Repo entirely 
* each "module" in a separate folder

**Comment by priceaj** [comment] 2018-11-28 16:37
Chris, please see my edits above.

The equivalent structure to the above of the current project is:

Repo (intERPrise)
|-QDBSQLF <- Database SQL File source
|--FileSource.sql
|-QDBSQLT <- Database SQL Trigger source
|--TriggerSource.sql
|-Transaction_server
|--QTSRPGLE <- Transaction server RPGLE source
|---TXNSVR.SQLRPGLE

**Comment by ChrisHird** [comment] 2018-11-28 16:41
I Think moving the DB (current base without Transport services) into a directory resolves the issue. Will look at that as I review the best option for GitHub > IDE integration.

**Comment by ChrisHird** [comment] 2018-11-28 17:53
The problem is the way RDi works with iProjects. I see the issue in that the intERPrise project also includes Transport_Services which is also shown in the iProject navigator as a separate project because we have added transport_Services.  GitHub is not affected by the limitations of RDi and the layout does make sense. I have created a new directory and moved the base content to it as well as adjusted the .gitignore. This will allow additional modules to be created in the future which will be separated by the directory structure. 

As this is a pure RDi issue (where it relates to iProjects) and not one we have any influence on for many of the possible contributors I am going to close this issue. If you manage to get IBM to change the iProjects implementation to support multi library projects we can review again.

I have created a new branch 'Chris_Transport' which shows the changes I have made. I will merge at some time in the future.

**Closed by ChrisHird** 2018-11-28 17:53 UTC

**Comment by ChrisHird** [comment] 2018-11-28 18:17
iProjects does allow you to have related projects, not looked at that? Also you could look at using the git perspective for updating GitHub not iProjects git options? I see where it can get pretty confusing. early days for using git with ILE based IBM i Open Source :-)

**Comment by ChrisHird** [comment] 2018-11-28 18:43
![image](https://user-images.githubusercontent.com/18249457/49174026-44437580-f313-11e8-875f-29f99c289b08.png)
This is now set up with separation between iProjects and NO duplicate Transport_Services. This meets your requirements without affecting the structure on GitHub.

I deleted the original project for intERPrise and rebuilt with the base being in Database_Services.
